// @vitest-environment node
import {readFile,readdir} from 'node:fs/promises';
import {randomBytes,createHash} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {beforeAll,afterAll,it,expect} from 'vitest';
const owner='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',guest='33333333-3333-4333-8333-333333333333';
let db:PGlite;
async function as(sql:string,p:unknown[]=[],user=owner,role='authenticated'){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);await db.exec(`set role ${role}`);try{return (await db.query<any>(sql,p)).rows;}finally{await db.exec('reset role');}}
const status=async(user=owner)=>(await as('select public.get_fitness_subscription() as s',[],user))[0].s;
const rotate=async(rev:number,notes=false,user=owner)=>{const token=randomBytes(32).toString('base64url');const hash=createHash('sha256').update(token).digest('hex');return {...(await as('select public.rotate_fitness_subscription($1,$2,$3) as s',[rev,notes,hash],user))[0].s,token};};
const update=async(rev:number,enabled:boolean,notes=false)=>(await as('select public.update_fitness_subscription($1,$2,$3) as s',[rev,enabled,notes]))[0].s;
async function feed(token:string){const h=(await db.query<any>("select encode(sha256(convert_to($1,'UTF8')),'hex') h",[token])).rows[0].h;return (await as('select life_console_private.read_fitness_feed($1) as s',[h],'','fitness_feed_reader'))[0].s;}
beforeAll(async()=>{db=new PGlite();await db.exec(await readFile(new URL('./fixtures/auth-shim.sql',import.meta.url),'utf8'));const dir=new URL('../../supabase/migrations/',import.meta.url);await db.exec(await readFile(new URL('0001_life_console.sql',dir),'utf8'));for(const suffix of ['_fitness_appointments.sql','_fitness_http_conflicts.sql','_fitness_subscription.sql','_fitness_all_day.sql','_fitness_subscription_all_day.sql']){const f=(await readdir(dir)).find(x=>x.endsWith(suffix));if(!f)throw Error('Missing '+suffix);await db.exec(await readFile(new URL(f,dir),'utf8'));}await db.query('insert into auth.users(id) values ($1),($2),($3)',[owner,other,guest]);await db.query('insert into life_console_private.fitness_owners(user_id) values ($1),($2)',[owner,other]);});
afterAll(async()=>{await db?.close();});
it('defaults disabled without exposing token and rejects anonymous/nonOwner',async()=>{expect(await status()).toEqual({enabled:false,includeNotes:false,revision:0});await expect(status(guest)).rejects.toThrow();await expect(as('select public.get_fitness_subscription()',[],'','anon')).rejects.toThrow();});
it('rotates one-time random tokens, stores only hash, rejects stale versions',async()=>{const a=await rotate(0);expect(a.token).toMatch(/^[A-Za-z0-9_-]{43}$/);expect(a.enabled).toBe(true);expect(a.revision).toBe(1);expect(await status()).not.toHaveProperty('token');expect(JSON.stringify((await db.query('select * from life_console_private.fitness_calendar_subscription')).rows)).not.toContain(a.token);expect((await feed(a.token)).events).toEqual([]);await expect(rotate(0)).rejects.toThrow();const b=await rotate(a.revision);expect(b.token).not.toBe(a.token);expect(await feed(a.token)).toBeNull();expect(await feed(b.token)).not.toBeNull();});
it('projects all live events, notes opt-in, scopes owner and soft deletion',async()=>{await as("select public.create_fitness_appointment('synthetic-operation-1','合成训练','2030-01-01T10:00Z','2030-01-01T11:00Z','合成地点','私密备注')");await as("select public.create_fitness_appointment('synthetic-operation-2','其他用户','2030-01-01T10:00Z','2030-01-01T11:00Z','','')",[],other);const a=await rotate((await status()).revision);const initial=await feed(a.token);expect(initial.events).toHaveLength(1);expect(initial.events[0].notes).toBeUndefined();expect(JSON.stringify(initial)).not.toContain(owner);await update(a.revision,true,true);const changed=await feed(a.token);expect(changed.events[0].notes).toBe('私密备注');expect(changed.sequence).toBeGreaterThan(initial.sequence);await as('select public.soft_delete_fitness_appointment($1,1)',[initial.events[0].id]);expect((await feed(a.token)).events).toEqual([]);});
it('disables immediately, blocks implicit restart, and Owner revocation blocks feed',async()=>{const a=await rotate((await status()).revision);const b=await update(a.revision,false);expect(await feed(a.token)).toBeNull();await expect(update(b.revision,true)).rejects.toThrow();const c=await rotate(b.revision);await db.query('update life_console_private.fitness_owners set enabled=false where user_id=$1',[owner]);expect(await feed(c.token)).toBeNull();await db.query('update life_console_private.fitness_owners set enabled=true where user_id=$1',[owner]);});
it('feed role cannot read tables, manage subscriptions or invoke Owner functions',async()=>{await expect(as('select * from public.fitness_appointments',[],'','fitness_feed_reader')).rejects.toThrow();await expect(as('select * from life_console_private.fitness_calendar_subscription',[],'','fitness_feed_reader')).rejects.toThrow();await expect(as("select public.rotate_fitness_subscription(0,false,repeat('a',64))",[],'','fitness_feed_reader')).rejects.toThrow();await expect(as("select life_console_private.read_fitness_feed(repeat('a',64))")).rejects.toThrow();});
it('rejects oversized projected snapshots inside SQL before returning them to the service',async()=>{const a=await rotate((await status()).revision,true);await db.query("insert into public.fitness_appointments(user_id,title,start_at,end_at,notes) select $1,'预算合成','2030-01-01T10:00Z','2030-01-01T11:00Z',repeat('😀',4000) from generate_series(1,400)",[owner]);try{const value=await feed(a.token);expect(value).toEqual({error:'budget_exceeded'});expect(JSON.stringify(value).length).toBeLessThan(100);}finally{await db.query("delete from public.fitness_appointments where title='预算合成'");}});

it('projects all-day Shanghai date boundaries without converting to timed events',async()=>{const row=(await as("select * from public.create_fitness_appointment('synthetic-all-day-1','合成全天','2030-04-30T16:00Z','2030-05-01T16:00Z','','','all_day')"))[0];try{const a=await rotate((await status()).revision);const event=(await feed(a.token)).events.find((e:any)=>e.id===row.id);expect(event.timeKind).toBe('all_day');expect(event.startDate).toBe('2030-05-01');expect(event.endDate).toBe('2030-05-02');}finally{await as('select public.soft_delete_fitness_appointment($1,1)',[row.id]);}});
