// @vitest-environment jsdom
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,beforeAll,it,expect,vi} from 'vitest';
import {CalendarSubscriptionSettings} from '../../src/features/fitness/CalendarSubscriptionSettings';
const state={enabled:false,includeNotes:false,revision:0};
const url='https://calendar.example.test/calendar/fitness/'+'a'.repeat(43)+'.ics';
function repo(){return {get:vi.fn(async()=>state),rotate:vi.fn(async()=>({...state,enabled:true,revision:1,url})),update:vi.fn(async()=>({...state,revision:2}))};}
beforeAll(()=>{HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};});afterEach(cleanup);
it('explains scope, notes off by default, confirms enable and only shows one-time link in memory',async()=>{const r=repo();render(<CalendarSubscriptionSettings repository={r}/>);fireEvent.click(screen.getByText('Apple 日历订阅'));await screen.findByText('未启用');expect((screen.getByLabelText('包含备注') as HTMLInputElement).checked).toBe(false);fireEvent.click(screen.getByText('启用订阅'));expect(r.rotate).not.toHaveBeenCalled();fireEvent.click(screen.getByText('确认启用'));await screen.findByDisplayValue(url);expect(r.rotate).toHaveBeenCalledWith({expectedRevision:0,includeNotes:false});expect(screen.queryByText('Apple 已同步')).toBeNull();fireEvent.click(screen.getByText('关闭'));expect(screen.queryByDisplayValue(url)).toBeNull();});
it('unknown save error preserves preference, blocks blind retry and requires status refresh',async()=>{const r=repo();r.rotate.mockRejectedValue(Error('network'));render(<CalendarSubscriptionSettings repository={r}/>);fireEvent.click(screen.getByText('Apple 日历订阅'));await screen.findByText('未启用');fireEvent.click(screen.getByLabelText('包含备注'));fireEvent.click(screen.getByText('启用订阅'));fireEvent.click(screen.getByText('确认启用'));await screen.findByRole('alert');expect((screen.getByLabelText('包含备注') as HTMLInputElement).checked).toBe(true);expect((screen.getByText('启用订阅') as HTMLButtonElement).disabled).toBe(true);fireEvent.click(screen.getByText('刷新订阅状态'));await waitFor(()=>expect(r.get).toHaveBeenCalledTimes(2));});
it('closing then reopening discards links and ignores an old asynchronous read',async()=>{const r=repo();let resolve:(x:typeof state)=>void=()=>{};r.get.mockImplementationOnce(()=>new Promise(done=>resolve=done));render(<CalendarSubscriptionSettings repository={r}/>);fireEvent.click(screen.getByText('Apple 日历订阅'));fireEvent.click(screen.getByText('关闭'));resolve({...state,enabled:true});fireEvent.click(screen.getByText('Apple 日历订阅'));await screen.findByText('未启用');expect(screen.queryByDisplayValue(url)).toBeNull();});
