/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["createSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createJournal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checkins/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["upsertCheckin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capture/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["previewCapture"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capture/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["commitCapture"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/confirmations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConfirmations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/purge-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPurgePlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/purge-confirmations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmPurge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journal-enrichments/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Build a per-entry send preview for optional DeepSeek semantic enrichment. This never contacts the network; it only binds a short-lived token to the current entry snapshot, provider, model, writable-field allowlist, prompt version, authorization version, and retry ceiling. */
        post: operations["previewJournalEnrichment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journal-enrichments/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Confirm a previously issued preview and create an idempotent local background job. Returns 202 immediately; the local saved journal is never blocked. Rejects a drifted source with SOURCE_CHANGED before any send. */
        post: operations["commitJournalEnrichment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journal-enrichments/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch a raw-free enrichment job status. */
        get: operations["getJournalEnrichment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journal-enrichments/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description User-initiated retry of a failed job. Returns immediately; the worker re-validates the source before any send. */
        post: operations["retryJournalEnrichment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        IdempotencyKey: string;
        /** @enum {string|null} */
        AnchorState: "complete" | "minimum" | "skipped" | null;
        /** @enum {string} */
        AnchorValue: "complete" | "minimum" | "skipped";
        Rating: number | null;
        RatingValue: number;
        Dashboard: {
            /** @constant */
            schema_version: 1;
            /** Format: date-time */
            generated_at: string;
            /** Format: date */
            date: string;
            today: {
                focus: {
                    title: string;
                    phase_label: string;
                };
                suggested_action: {
                    id: string;
                    label: string;
                    writable: boolean;
                } | null;
                anchors: {
                    wake: components["schemas"]["AnchorState"];
                    body_light: components["schemas"]["AnchorState"];
                    life_action: components["schemas"]["AnchorState"];
                    wind_down: components["schemas"]["AnchorState"];
                };
                daily_revision: number | null;
                confirmations: components["schemas"]["Confirmation"][];
            };
            progress: {
                ratings: {
                    /** Format: date */
                    date: string;
                    sleep_quality: components["schemas"]["Rating"];
                    energy: components["schemas"]["Rating"];
                    mood: components["schemas"]["Rating"];
                    life_feeling: components["schemas"]["Rating"];
                }[];
                sleep: {
                    /** Format: date */
                    date: string;
                    sleep_time: string | null;
                    wake_time: string | null;
                    out_of_bed_time: string | null;
                }[];
                sample_counts: {
                    daily: number;
                    missing: number;
                };
            };
            records: {
                recent_journals: {
                    /** Format: date */
                    date: string;
                    title: string;
                    summary: string;
                }[];
            };
            system: {
                /** @enum {string} */
                hub: "ready" | "unavailable";
                /** @enum {string} */
                icloud: "readable" | "writable" | "partial" | "unavailable";
                /** @enum {string} */
                automation: "ready" | "attention" | "unknown";
                /** @enum {string} */
                backup: "ready" | "attention" | "unknown";
                /** @enum {string} */
                google: "paused" | "on_demand";
                /** @enum {string} */
                mobile: "pending";
            };
            source_revisions: {
                [key: string]: string;
            };
        };
        JournalRequest: {
            /** @constant */
            schema_version: 1;
            idempotency_key: components["schemas"]["IdempotencyKey"];
            /** Format: date */
            event_date: string;
            event_time?: string | null;
            /** @enum {string} */
            time_precision: "exact" | "approximate" | "unknown";
            text: string;
            title?: string;
            summary?: string;
            facts?: string[];
            feelings?: string[];
            people?: string[];
            places?: string[];
            themes?: string[];
            tags?: string[];
        };
        CheckinRequest: {
            /** @constant */
            schema_version: 1;
            idempotency_key: components["schemas"]["IdempotencyKey"];
            expect_revision: number | null;
            fields: {
                sleep_time?: string;
                wake_time?: string;
                out_of_bed_time?: string;
                sleep_quality?: components["schemas"]["RatingValue"];
                energy?: components["schemas"]["RatingValue"];
                mood?: components["schemas"]["RatingValue"];
                life_feeling?: components["schemas"]["RatingValue"];
                /** @enum {string} */
                awake_in_bed?: "yes" | "no";
                wake?: components["schemas"]["AnchorValue"];
                body_light?: components["schemas"]["AnchorValue"];
                life_action?: components["schemas"]["AnchorValue"];
                wind_down?: components["schemas"]["AnchorValue"];
                note_summary?: string;
            };
        };
        CapturePreview: {
            /** @constant */
            schema_version: 1;
            /** @enum {string} */
            state: "available" | "handoff_required" | "unavailable";
            message: string;
            preview_token?: string;
            /** @enum {string} */
            intent?: "journal" | "checkin" | "mixed" | "unknown";
            preview?: {
                [key: string]: unknown;
            };
        };
        CheckinConflict: {
            /** Format: date */
            target_key: string;
            current_revision: number | null;
            current: {
                sleep_time?: string | null;
                wake_time?: string | null;
                out_of_bed_time?: string | null;
                sleep_quality?: components["schemas"]["Rating"];
                energy?: components["schemas"]["Rating"];
                mood?: components["schemas"]["Rating"];
                life_feeling?: components["schemas"]["Rating"];
                /** @enum {string|null} */
                awake_in_bed?: "yes" | "no" | null;
                wake?: components["schemas"]["AnchorState"];
                body_light?: components["schemas"]["AnchorState"];
                life_action?: components["schemas"]["AnchorState"];
                wind_down?: components["schemas"]["AnchorState"];
            };
            submitted: {
                sleep_time?: string;
                wake_time?: string;
                out_of_bed_time?: string;
                sleep_quality?: components["schemas"]["RatingValue"];
                energy?: components["schemas"]["RatingValue"];
                mood?: components["schemas"]["RatingValue"];
                life_feeling?: components["schemas"]["RatingValue"];
                /** @enum {string} */
                awake_in_bed?: "yes" | "no";
                wake?: components["schemas"]["AnchorValue"];
                body_light?: components["schemas"]["AnchorValue"];
                life_action?: components["schemas"]["AnchorValue"];
                wind_down?: components["schemas"]["AnchorValue"];
            };
        };
        Confirmation: {
            id: string;
            /** @enum {string} */
            type: "revision_conflict" | "health_conflict" | "purge_plan" | "goal_change" | "service_issue";
            title: string;
            message: string;
            action_label: string;
        };
        PurgePlan: {
            /** @constant */
            schema_version: 1;
            plan_id: string;
            /** @enum {string} */
            target_type: "journal" | "daily_checkin" | "weekly_review" | "phase_review";
            target_key: string;
            expect_revision: number;
            plan_etag: string;
            scope_summary: string;
            confirmation_text: string;
            historical_copies_notice: string;
        };
        /** @enum {string} */
        EnrichmentModel: "deepseek-v4-flash" | "deepseek-v4-pro";
        /** @enum {string} */
        EnrichmentField: "title" | "summary" | "facts" | "feelings" | "people" | "places" | "themes" | "tags";
        EnrichmentPreview: {
            /** @constant */
            schema_version: 1;
            preview_token: string;
            /** Format: date-time */
            expires_at: string;
            journal_id: string;
            /** @constant */
            provider: "deepseek";
            model: components["schemas"]["EnrichmentModel"];
            prompt_version: string;
            authorization_version: string;
            max_retries: number;
            writable_fields: components["schemas"]["EnrichmentField"][];
            disclosures: string[];
        };
        EnrichmentJob: {
            /** @constant */
            schema_version: 1;
            job_id: string;
            journal_id: string;
            /** @constant */
            provider: "deepseek";
            model: components["schemas"]["EnrichmentModel"];
            prompt_version: string;
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed";
            attempts: number;
            max_retries: number;
            /** @enum {string|null} */
            failure_code?: "PROVIDER_UNAVAILABLE" | "MODEL_OUTPUT_INVALID" | "SOURCE_CHANGED" | null;
            /** Format: date-time */
            updated_at?: string;
        };
        CommandReceipt: {
            request_id: string;
            command_id: string;
            /** @enum {string} */
            action: "created" | "updated" | "unchanged";
            source: {
                /** @constant */
                state: "saved";
                revision: number | null;
            };
            /** @enum {string} */
            read_model: "current" | "pending_refresh";
            message: string;
        };
        ErrorResponse: {
            request_id: string;
            conflict?: components["schemas"]["CheckinConflict"];
            error: {
                /** @enum {string} */
                code: "INVALID_REQUEST" | "REVISION_CONFLICT" | "SOURCE_INVALID" | "SOURCE_CHANGED" | "NOT_FOUND" | "HUB_UNAVAILABLE" | "TOOL_TIMEOUT" | "PREVIEW_EXPIRED";
                message: string;
                retryable: boolean;
            };
        };
    };
    responses: {
        /** @description Source write completed or was idempotently unchanged. */
        CommandSuccess: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CommandReceipt"];
            };
        };
        /** @description Request failed schema or policy validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Local session, CSRF token, or same-origin policy failed. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Revision or source state conflict. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The requested local resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Hub or iCloud source is unavailable. */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        CsrfHeader: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hub is ready without reading personal content. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ready";
                        /** @constant */
                        schema_version: 1;
                    };
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Same-origin local session. Response must use Cache-Control no-store. */
            200: {
                headers: {
                    /** @description HttpOnly SameSite=Strict local session cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        schema_version: 1;
                        csrf_token: string;
                        /** Format: date-time */
                        expires_at: string;
                    };
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Whitelisted local dashboard snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            403: components["responses"]["Forbidden"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createJournal: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JournalRequest"];
            };
        };
        responses: {
            200: components["responses"]["CommandSuccess"];
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    upsertCheckin: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
            };
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckinRequest"];
            };
        };
        responses: {
            200: components["responses"]["CommandSuccess"];
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    previewCapture: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @constant */
                    schema_version: 1;
                    text: string;
                    context_etag: string;
                };
            };
        };
        responses: {
            /** @description Preview or safe handoff state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapturePreview"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    commitCapture: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @constant */
                    schema_version: 1;
                    idempotency_key: components["schemas"]["IdempotencyKey"];
                    preview_token: string;
                };
            };
        };
        responses: {
            200: components["responses"]["CommandSuccess"];
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getConfirmations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Safe confirmation projections without raw content. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        schema_version: 1;
                        items: components["schemas"]["Confirmation"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createPurgePlan: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @constant */
                    schema_version: 1;
                    /** @enum {string} */
                    target_type: "journal" | "daily_checkin" | "weekly_review" | "phase_review";
                    target_key: string;
                };
            };
        };
        responses: {
            /** @description Safe deletion scope preview without raw content. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurgePlan"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    confirmPurge: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @constant */
                    schema_version: 1;
                    idempotency_key: components["schemas"]["IdempotencyKey"];
                    plan_id: string;
                    confirmation_text: string;
                    expect_revision: number;
                    plan_etag: string;
                    /** @constant */
                    acknowledge_historical_copies: true;
                };
            };
        };
        responses: {
            200: components["responses"]["CommandSuccess"];
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    previewJournalEnrichment: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @constant */
                    schema_version: 1;
                    journal_id: string;
                    model?: components["schemas"]["EnrichmentModel"];
                };
            };
        };
        responses: {
            /** @description Offline send-scope preview with a short-lived preview token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichmentPreview"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    commitJournalEnrichment: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @constant */
                    schema_version: 1;
                    idempotency_key: components["schemas"]["IdempotencyKey"];
                    preview_token: string;
                };
            };
        };
        responses: {
            /** @description Local background job accepted; no external request has been sent yet. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichmentJob"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getJournalEnrichment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raw-free job status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichmentJob"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    retryJournalEnrichment: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @constant */
                    schema_version: 1;
                    idempotency_key: components["schemas"]["IdempotencyKey"];
                };
            };
        };
        responses: {
            /** @description Retry accepted; no external request has been sent yet. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichmentJob"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
}
