/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSitesOwner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSitesCsrf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSitesDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSitesBootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSitesSystemStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSitesGoals"];
        put?: never;
        post: operations["createSitesGoal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteSitesGoal"];
        options?: never;
        head?: never;
        patch: operations["updateSitesGoal"];
        trace?: never;
    };
    "/api/v1/journals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSitesJournals"];
        put?: never;
        post: operations["createSitesJournal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get: operations["getSitesJournal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSitesJournal"];
        trace?: never;
    };
    "/api/v1/journals/{id}/delete-plan": {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
                "If-Match": components["parameters"]["RevisionHeader"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["planSitesJournalDeletion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journals/{id}/delete-plan/cancel": {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
                "If-Match": components["parameters"]["RevisionHeader"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelSitesJournalDeletion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journals/{id}/purge": {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
                "If-Match": components["parameters"]["RevisionHeader"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["purgeSitesJournal"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/daily-checkins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSitesDailyCheckins"];
        put?: never;
        post: operations["createSitesDailyCheckin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/daily-checkins/by-date/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSitesDailyCheckinByDate"];
        trace?: never;
    };
    "/api/v1/weekly-reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSitesWeeklyReviews"];
        put?: never;
        post: operations["createSitesWeeklyReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/phase-reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSitesPhaseReviews"];
        put?: never;
        post: operations["createSitesPhaseReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSitesHealthDays"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/days/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get: operations["getSitesHealthDay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSitesHealthDay"];
        trace?: never;
    };
    "/api/v1/health/days/{id}/segments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get: operations["listSitesHealthSegments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importSitesHealthDay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSitesAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backup/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSitesBackupQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backup/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["triggerSitesFullBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backup/queue/{id}/payload": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get: operations["getSitesBackupPayload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backup/queue/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reportSitesBackupOutcome"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crypto/recovery-pack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSitesRecoveryPack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crypto/verify-recovery-pack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifySitesRecoveryPack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crypto/rotate-keks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rotateSitesKeks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/migration/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSitesMigrationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/migration/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["planSitesMigration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/migration/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateSitesMigration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/migration/switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["switchSitesTruthSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/migration/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rollbackSitesTruthSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Owner: {
            owner_hash: string;
            /** @constant */
            role: "owner";
            /** @constant */
            version: "2.0.0";
        };
        Csrf: {
            owner_hash: string;
            token: string;
            /** Format: date-time */
            expires_at: string;
        };
        Mutation: {
            id: string;
            revision?: number;
            /** Format: date-time */
            updated_at?: string;
        } & {
            [key: string]: unknown;
        };
        ListResponse: {
            items: Record<string, never>[];
        };
        Bootstrap: {
            dashboard: Record<string, never>;
            system: components["schemas"]["SystemStatus"];
            goals: Record<string, never>[];
            journals: Record<string, never>[];
            health: Record<string, never>[];
        };
        SystemStatus: {
            /** @constant */
            version: "2.0.0";
            /** @constant */
            mode: "sites-api";
            /** @enum {string} */
            source_truth: "ICLOUD_PRIMARY" | "SITES_D1_PRIMARY";
            migration: Record<string, never>;
            encryption: Record<string, never>;
            backup: Record<string, never>;
        } & {
            [key: string]: unknown;
        };
        Error: {
            request_id: string;
            error: {
                code: string;
                message: string;
                retryable: boolean;
            } & {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Mutation receipt with revision where applicable. */
        Mutation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Mutation"];
            };
        };
        /** @description Owner session required. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Revision or state conflict. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ResourceId: string;
        CsrfHeader: string;
        IdempotencyHeader: string;
        RevisionHeader: number;
    };
    requestBodies: {
        JsonObject: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSitesOwner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owner identity hash */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Owner"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSitesCsrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Short-lived CSRF token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Csrf"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSitesDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Whitelisted D1 dashboard projection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSitesBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Minimum first-screen projection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bootstrap"];
                };
            };
        };
    };
    getSitesSystemStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Truth source */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
    listSitesGoals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Goal list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
        };
    };
    createSitesGoal: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
                "Idempotency-Key": components["parameters"]["IdempotencyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Mutation"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteSitesGoal: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
                "If-Match": components["parameters"]["RevisionHeader"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Mutation"];
            409: components["responses"]["Conflict"];
        };
    };
    updateSitesGoal: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
                "If-Match": components["parameters"]["RevisionHeader"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Mutation"];
            409: components["responses"]["Conflict"];
        };
    };
    listSitesJournals: {
        parameters: {
            query?: {
                date_from?: string;
                date_to?: string;
                mood?: string;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata-only journal list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
        };
    };
    createSitesJournal: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
                "Idempotency-Key": components["parameters"]["IdempotencyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Mutation"];
            409: components["responses"]["Conflict"];
        };
    };
    getSitesJournal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Decrypted owner-only journal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateSitesJournal: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
                "If-Match": components["parameters"]["RevisionHeader"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Mutation"];
            409: components["responses"]["Conflict"];
        };
    };
    planSitesJournalDeletion: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
                "If-Match": components["parameters"]["RevisionHeader"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Mutation"];
        };
    };
    cancelSitesJournalDeletion: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
                "If-Match": components["parameters"]["RevisionHeader"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Mutation"];
        };
    };
    purgeSitesJournal: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
                "If-Match": components["parameters"]["RevisionHeader"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Mutation"];
            409: components["responses"]["Conflict"];
        };
    };
    listSitesDailyCheckins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
        };
    };
    createSitesDailyCheckin: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
                "Idempotency-Key": components["parameters"]["IdempotencyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Mutation"];
        };
    };
    updateSitesDailyCheckinByDate: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
                "If-Match": components["parameters"]["RevisionHeader"];
            };
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Mutation"];
            409: components["responses"]["Conflict"];
        };
    };
    listSitesWeeklyReviews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Weekly list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
        };
    };
    createSitesWeeklyReview: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
                "Idempotency-Key": components["parameters"]["IdempotencyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Mutation"];
        };
    };
    listSitesPhaseReviews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Phase list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
        };
    };
    createSitesPhaseReview: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
                "Idempotency-Key": components["parameters"]["IdempotencyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Mutation"];
        };
    };
    listSitesHealthDays: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Minimum plaintext health trend */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
        };
    };
    getSitesHealthDay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Decrypted owner-only health detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateSitesHealthDay: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
                "If-Match": components["parameters"]["RevisionHeader"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Mutation"];
            409: components["responses"]["Conflict"];
        };
    };
    listSitesHealthSegments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Decrypted owner-only segment list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    importSitesHealthDay: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
                "Idempotency-Key": components["parameters"]["IdempotencyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Mutation"];
        };
    };
    listSitesAuditEvents: {
        parameters: {
            query?: {
                size?: number;
                resource_type?: string;
                action?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raw-free audit list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
        };
    };
    listSitesBackupQueue: {
        parameters: {
            query?: {
                size?: number;
                status?: "PENDING" | "SUCCESS" | "FAILED" | "RETRYING" | "SKIPPED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backup queue metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
        };
    };
    triggerSitesFullBackup: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            /** @description Encrypted R2 backup receipt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    getSitesBackupPayload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owner-only decrypted cold-backup payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    reportSitesBackupOutcome: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Mutation"];
            404: components["responses"]["NotFound"];
        };
    };
    createSitesRecoveryPack: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            /** @description Encrypted recovery pack receipt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    verifySitesRecoveryPack: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            /** @description Recovery sample verification result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    rotateSitesKeks: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            /** @description Re-encryption result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Target KEK must be preconfigured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSitesMigrationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Migration state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    planSitesMigration: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Mutation"];
        };
    };
    validateSitesMigration: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Mutation"];
        };
    };
    switchSitesTruthSource: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Mutation"];
            409: components["responses"]["Conflict"];
        };
    };
    rollbackSitesTruthSource: {
        parameters: {
            query?: never;
            header: {
                "X-Life-CSRF": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Mutation"];
            409: components["responses"]["Conflict"];
        };
    };
}
